{{- $env := .Values.werf.env }}
{{- $host := pluck $env .Values.host | first | default .Values.host._default }}
{{- if hasPrefix "review" $env }}
{{- $host = ( printf "%s.%s" $env (pluck "dev" .Values.host | first | default .Values.host._default ) | lower ) }}
{{- end }}
{{- $ingressClassName := pluck .Values.global.env .Values.ingressClassName | first | default .Values.ingressClassName._default | quote }}
{{- $targetCluster := include "targetCluster" . | trim }}
{{- $isProduction := eq .Values.global.env "production" }}
{{- $ruHost := include "ruHost" $host | trim }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuf-router
spec:
  ingressClassName: {{ $ingressClassName }}
  tls:
  - hosts:
{{- if $isProduction }}
{{- if eq $targetCluster "ru" }}
      - {{ $ruHost }}
{{- else }}
      - {{ $host }}
{{- end }}
    secretName: tls-{{ $host }}
{{- else }}
      - {{ $host }}
      - ru-{{ $host }}
    secretName: {{ pluck .Values.global.env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}
{{- end }}
  rules:
{{- if $isProduction }}
{{- if eq $targetCluster "ru" }}
  - host: {{ $ruHost }}
{{- else }}
  - host: {{ $host }}
{{- end }}
    http:
      paths:
      - path: /targets
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- else }}
  - host: {{ $host }}
    http:
      paths:
      - path: /targets
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
  - host: ru-{{ $host }}
    http:
      paths:
      - path: /targets
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
      - path: /download
        pathType: Prefix
        backend:
          service:
            name: tuf-router
            port:
              name: http
{{- end }}
