{{- $env := .Values.global.env }}
{{- $host := pluck $env .Values.host | first | default .Values.host._default }}
{{- $ingressClassName := pluck $env .Values.ingressClassName | first | default .Values.ingressClassName._default | quote }}
{{- $targetCluster := include "targetCluster" . | trim }}
{{- $isProduction := eq $env "production" }}
{{- $renderEU := or (not $isProduction) (eq $targetCluster "eu") }}
{{- $renderRU := or (not $isProduction) (eq $targetCluster "ru") }}
{{- $ruHost := include "ruHost" $host | trim }}
{{- if $renderEU }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
{{- if $isProduction }}
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
{{- else }}
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/dex-authenticator/sign_in
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Chart.Name }}-dex-authenticator.{{ .Chart.Name }}-{{ $env }}.svc.cluster.local/dex-authenticator/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
{{- end }}
spec:
  ingressClassName: {{ $ingressClassName }}
  tls:
  - hosts:
      - {{ $host }}
{{- if $isProduction }}
      - www.{{ $host }}
    secretName: tls-{{ $host }}
{{- else }}
    secretName: {{ pluck $env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}
{{- end }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 80
{{- end }}
{{- if and $renderEU $renderRU }}
---
{{- end }}
{{- if $renderRU }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ru
{{- if not $isProduction }}
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/dex-authenticator/sign_in
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Chart.Name }}-ru-dex-authenticator.{{ .Chart.Name }}-{{ $env }}.svc.cluster.local/dex-authenticator/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
{{- end }}
spec:
  ingressClassName: {{ $ingressClassName }}
  tls:
  - hosts:
{{- if $isProduction }}
      - {{ $ruHost }}
    secretName: tls-{{ $host }}
{{- else }}
      - ru-{{ $host }}
    secretName: {{ pluck $env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}
{{- end }}
  rules:
{{- if $isProduction }}
  - host: {{ $ruHost }}
{{- else }}
  - host: ru-{{ $host }}
{{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 80
{{- end }}
{{- if $isProduction }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
spec:
  secretName: tls-{{ $host }}
  issuerRef:
    kind: ClusterIssuer
{{- if hasPrefix "review" $env }}
    name: letsencrypt-staging
{{- else }}
    name: letsencrypt-standalone-geo
{{- end }}
{{- if eq $targetCluster "ru" }}
  commonName: {{ $ruHost }}
  dnsNames:
  - {{ $ruHost }}
{{- else }}
  commonName: {{ $host }}
  dnsNames:
  - {{ $host }}
  - www.{{ $host }}
{{- end }}
{{- end }}
{{- if ne $env "production" }}
---
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
  name: {{ .Chart.Name }}
spec:
  applicationDomain: {{ $host }}
  sendAuthorizationHeader: false
  applicationIngressCertificateSecretName: {{ pluck $env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}
  applicationIngressClassName: "nginx"
  keepUsersLoggedInFor: "720h"
---
apiVersion: deckhouse.io/v1alpha1
kind: DexAuthenticator
metadata:
  name: {{ .Chart.Name }}-ru
spec:
  applicationDomain: ru-{{ $host }}
  sendAuthorizationHeader: false
  applicationIngressCertificateSecretName: {{ pluck $env .Values.ingressSecretName | first | default .Values.ingressSecretName._default }}
  applicationIngressClassName: "nginx"
  keepUsersLoggedInFor: "720h"
{{- end }}
