version: "3"

silent: true

includes:
  e2e:
    taskfile: https://raw.githubusercontent.com/werf/common-ci/refs/heads/chore/taskfile/add-taskfile/Taskfile.format_lint.yml
    flatten: true
    vars:
      paths: "tests/**"

tasks:
  test:e2e:
    desc: "Run client e2e test."
    cmd: ginkgo -p --keep-going --cover --coverpkg=../client/...,../server/... --output-dir={{.outputDir}} ./...
    vars:
      outputDir: '{{.outputDir | default "../tests_coverage/e2e" }}'
