version: "3"

silent: true

includes:
  e2e:
    taskfile: https://raw.githubusercontent.com/werf/common-ci/refs/heads/main/Taskfile.format_lint.yml
    flatten: true
    vars:
      paths: "tests/**"

tasks:
  test:e2e:
    desc: "Run client e2e test."
    cmd: ginkgo --vv --keep-going --cover --covermode=atomic --coverpkg=github.com/werf/trdl/client/...,github.com/werf/trdl/server/... --output-dir={{.outputDir}} ./...
    vars:
      outputDir: '{{.outputDir | default "../tests_coverage/e2e" }}'
