version: "3"

silent: true

tasks:
  format:
    desc: 'Run all code formatters. Important vars: "paths".'
    run: once
    cmds:
      - task: format:gci
      - task: format:gofumpt
      - task: format:prettier

  format:gci:
    desc: 'Format code with gci. Important vars: "paths".'
    cmds:
      - gci write -s standard -s default -s 'Prefix(github.com/werf/)' {{.CLI_ARGS}} {{.paths | default "pkg/ cmd/ common/"}}

  format:gofumpt:
    desc: 'Format code with gofumpt. Important vars: "paths".'
    cmds:
      - gofumpt -extra -w {{.CLI_ARGS}} {{.paths | default "pkg/ cmd/ common/"}}

  format:prettier:
    desc: "Format with prettier."
    deps:
      - format:prettier:yaml

  format:prettier:yaml:
    desc: "Check if yaml files are prettier-formatted."
    cmds:
      - docker run --rm -v $(pwd):/work tmknom/prettier -w "**/*.yaml"

  lint:
    desc: 'Run all linters in parallel. Important vars: "paths".'
    deps:
      - lint:golangci-lint
      - lint:prettier

  lint:golangci-lint:go:
    desc: 'Lint with golangci-lint. Important vars: "paths".'
    cmds:
      - golangci-lint run {{.CLI_ARGS}} --config ../.golangci.yaml {{.paths | default "./..."}}
    env:
      CGO_ENABLED: "0"

  _lint:golangci-lint:go:
    deps:
      - task: lint:golangci-lint:go
        vars:
          paths: "{{.paths}}"

  lint:golangci-lint:
    desc: 'Lint with golangci-lint. Important vars: "paths".'
    deps:
      - task: _lint:golangci-lint:go
        vars:
          paths: "{{.paths}}"

  lint:prettier:
    desc: "Check if prettier-formatted."
    deps:
      - lint:prettier:yaml

  lint:prettier:yaml:
    desc: "Check if yaml files are prettier-formatted."
    cmds:
      - docker run --rm -v $(pwd):/work tmknom/prettier -c "**/*.yaml"

  build:
    desc: "Build client dev binary."
    run: once
    cmds:
      - task: build:dev:{{OS}}:{{ARCH}}
        vars:
          extraGoBuildArgs: "{{.extraGoBuildArgs}}"
          raceDetectorEnabled: '{{.raceDetectorEnabled | default "false"}}'
          outputDir: ../bin/trdl-vault

  build:all:
    desc: "Build all client binaries."
    deps:
      - build:dev
      - build:dist

  build:dev:
    desc: "Build all client dev binaries."
    cmds:
      - task: build:dev:linux:amd64
      - task: build:dev:linux:arm64
      - task: build:dev:darwin:amd64
      - task: build:dev:darwin:arm64
      - task: build:dev:windows:amd64

  build:dist:
    desc: "Build all client release binaries."
    cmds:
      - task: build:dist:linux:amd64
      - task: build:dist:linux:arm64
      - task: build:dist:darwin:amd64
      - task: build:dist:darwin:arm64
      - task: build:dist:windows:amd64

  build:dev:linux:amd64:
    desc: "Build client dev binary for linux/amd64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "linux"
          targetArch: "amd64"
          outputDir: "{{.outputDir}}"

  build:dev:linux:arm64:
    desc: "Build client dev binary for linux/arm64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "linux"
          targetArch: "arm64"
          outputDir: "{{.outputDir}}"

  build:dev:darwin:amd64:
    desc: "Build client dev binary for darwin/amd64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "darwin"
          targetArch: "amd64"
          outputDir: "{{.outputDir}}"

  build:dev:darwin:arm64:
    desc: "Build client dev binary for darwin/arm64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "darwin"
          targetArch: "arm64"
          outputDir: "{{.outputDir}}"

  build:dev:windows:amd64:
    desc: "Build client dev binary for windows/amd64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "windows"
          targetArch: "amd64"
          outputDir: "{{.outputDir}}"

  build:dist:linux:amd64:
    desc: "Build client release binary for linux/amd64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "linux"
          targetArch: "amd64"
          extraGoBuildArgs: -ldflags="-s -w"
          outputDir: "dist/{{.version}}/linux-amd64/bin/"

  build:dist:linux:arm64:
    desc: "Build client release binary for linux/arm64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "linux"
          targetArch: "arm64"
          extraGoBuildArgs: -ldflags="-s -w"
          outputDir: "dist/{{.version}}/linux-arm64/bin/"

  build:dist:darwin:amd64:
    desc: "Build client release binary for darwin/amd64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "darwin"
          targetArch: "amd64"
          extraGoBuildArgs: -ldflags="-s -w"
          outputDir: "dist/{{.version}}/darwin-amd64/bin/"

  build:dist:darwin:arm64:
    desc: "Build client release binary for darwin/arm64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "darwin"
          targetArch: "arm64"
          extraGoBuildArgs: -ldflags="-s -w"
          outputDir: "dist/{{.version}}/darwin-arm64/bin/"

  build:dist:windows:amd64:
    desc: "Build client release binary for windows/amd64."
    cmds:
      - task: _build:go
        vars:
          targetOS: "windows"
          targetArch: "amd64"
          extraGoBuildArgs: -ldflags="-s -w"
          outputDir: "dist/{{.version}}/windows-amd64/bin/"

  _build:go:
    internal: true
    cmds:
      - |
        go build -o {{.outputDir | default (printf "./bin/%s/%s-%s" .version .targetOS .targetArch)}}/trdl-vault{{if (eq .targetOS "windows")}}.exe{{end}} \
        {{.extraGoBuildArgs}} {{.CLI_ARGS}} github.com/werf/trdl/release/cmd/trdl-vault
    env:
      GOOS: "{{.targetOS}}"
      GOARCH: "{{.targetArch}}"
      CGO_ENABLED: 0

  verify:dist:binaries:
    desc: "Verify that the distributable binaries are built and have correct platform/arch."
    cmds:
      - ./scripts/verify-dist-binaries.sh {{.version}}

  clean:binaries:
    desc: "Clean all built binaries."
    deps:
      - clean:binaries:dev
      - clean:binaries:dist

  clean:binaries:dev:
    desc: "Clean built dev binaries."
    cmds:
      - rm -rf ./bin

  clean:binaries:dist:
    desc: "Clean built release binaries."
    cmds:
      - rm -rf ./dist
