# See: https://yamllint.readthedocs.io/en/stable/

rules:
  document-end: disable
  document-start:
    level: warning
    present: false
  line-length:
    level: warning
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
ignore:
  - .licenses/
