version: '3'

silent: true

vars:
  DOCKER_RUN: docker run --rm -v $(pwd):/app -w /app node:18

tasks:
  _npm:install:
    cmds:
      - |
        {{.DOCKER_RUN}} sh -c '
          if [ ! -d node_modules ]; then
            echo "node_modules not found, installing dependencies..."
            npm ci
          else
            echo "Dependencies already installed"
          fi
        '

  format:write:
    desc: Run prettier --write
    deps: [_npm:install]
    cmds:
      - '{{.DOCKER_RUN}} npm run format:write'

  format:check:
    desc: Run prettier --check
    deps: [_npm:install]
    cmds:
      - '{{.DOCKER_RUN}} npm run format:check'

  lint:
    desc: Run eslint
    deps: [_npm:install]
    cmds:
      - '{{.DOCKER_RUN}} npm run lint'

  package:
    desc: Build with rollup
    deps: [_npm:install]
    cmds:
      - '{{.DOCKER_RUN}} npm run package'

  test:
    desc: Run jest tests
    deps: [_npm:install]
    cmds:
      - "{{.DOCKER_RUN}} sh -c 'npm run test'"

  coverage:
    desc: Generate coverage badge
    deps: [test]
    cmds:
      - mkdir ./badges || true
      - "{{.DOCKER_RUN}} sh -c 'npm run coverage'"

  all:
    desc: Run formatter, linter, tests, coverage and package
    deps: [_npm:install]
    cmds:
      - task: format:write
      - task: lint
      - task: test
      - task: coverage
      - task: package
