source "https://rubygems.org"


group :jekyll_plugins do
  gem "jekyll-assets", '4.0.0.alpha-theme.0', git: "https://github.com/flant/third-party-jekyll-assets.git"
  gem "jekyll-flant-plugins"
  gem "jekyll-flant-theme"
end

gem "jekyll"
gem "kramdown-parser-gfm"

gem "sprockets", '>= 4.0.2'
gem "nokogiri", ">= 1.10.8"
gem "kramdown", ">= 2.3.0"

gem "html-proofer"
