source "https://rubygems.org"

gem "jekyll-assets"
gem "jekyll", ">= 3.9.2"
gem "kramdown-parser-gfm"

gem "sprockets", "~> 4.2", ">= 4.2.0"
gem "nokogiri", ">= 1.10.8"
gem "kramdown", ">= 2.3.0"

gem "html-proofer"
