version: "3"

vars:
  built_trdl_bin_path: "trdl"
  reference_sidebar_path: "./_data/sidebars/reference.yml"
  cli_partial_path: "./_data/sidebars/_cli.yml"
  vault_plugin_partial_path: "./_data/sidebars/_vault_plugin.yml"
  reference_partial_path: "./_data/sidebars/_reference.yml"

tasks:
  regen_reference:
    desc: "Regenerate reference"
    cmds:
      - task: _regen_reference_cli
      - task: _regen_reference_vault_plugin
      - task: _compile

  _regen_reference_cli:
    desc: "Regenerate reference CLI"
    cmds:
      - cd ../client && go install github.com/werf/trdl/client/cmd/trdl
      - "{{.built_trdl_bin_path}} docs ."

  _regen_reference_vault_plugin:
    desc: "Regenerate reference Vault plugin"
    cmds:
      - cd ../server && go install github.com/werf/trdl/server/cmd/vault-plugin-docs
      - vault-plugin-docs generate-jekyll --base-pages-url /reference/vault_plugin --includes-dir _includes/reference/vault_plugin --pages-dir pages_en/reference/vault_plugin --sidebar-yml-path _data/sidebars/_vault_plugin.yml

  _compile:
    desc: "Compile reference sidebar"
    cmds:
      - |
        echo "# This file is generated by the docs/Taskfile" > {{.reference_sidebar_path}}
        echo "# DO NOT EDIT!" >> {{.reference_sidebar_path}}
        echo "" >> {{.reference_sidebar_path}}
        echo "# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting." >> {{.reference_sidebar_path}}
        echo "" >> {{.reference_sidebar_path}}
        cat {{.cli_partial_path}} >> {{.reference_sidebar_path}}
        echo "" >> {{.reference_sidebar_path}}
        cat {{.vault_plugin_partial_path}} >> {{.reference_sidebar_path}}
        echo "" >> {{.reference_sidebar_path}}
        cat {{.reference_partial_path}} >> {{.reference_sidebar_path}}

  lint:
    desc: 'Run all linters in parallel. Important vars: "paths".'
    deps:
      - lint:prettier

  lint:prettier:
    desc: "Check if prettier-formatted."
    deps:
      - lint:prettier:yaml

  lint:prettier:yaml:
    desc: "Check if yaml files are prettier-formatted."
    cmds:
      - docker run --rm -v $(pwd):/work -v ./../.prettierignore/:/work/.prettierignore tmknom/prettier -c "**/*.yaml" "**/*.yml"

  format:
    desc: 'Run all code formatters. Important vars: "paths".'
    run: once
    cmds:
      - task: format:prettier

  format:prettier:
    desc: "Format with prettier."
    deps:
      - format:prettier:yaml

  format:prettier:yaml:
    desc: "Check if yaml files are prettier-formatted."
    cmds:
      - docker run --rm -v $(pwd):/work -v ./../.prettierignore/:/work/.prettierignore tmknom/prettier -w "**/*.yaml" "**/*.yml"
