name: Actions. Lint

on: [push]

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          task --yes actions:lint
          task --yes actions:format:check
