name: Tests
on:
  push:
    branches: [main]
    paths:
      - "client/scripts/ci"
      - "client/scripts/minio"
      - ".github/workflows/tests.yml"
      - "**/*.go"
      - go.mod
  schedule:
    - cron: "0 8 * * *"
  pull_request:
  repository_dispatch:
    types: [tests]
  workflow_dispatch:

jobs:
  unit_server:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg

      - name: Set up git config
        run: task ci:setup:git-config

      - name: Install 3p-git-signatures
        run: task ci:install:3p-git-signatures

      - name: Install ginkgo
        working-directory: server
        run: task -p deps:install:ginkgo

      - name: Test
        run: task -p test:unit
        env:
          TRDL_TEST_COVERAGE_DIR: ${{github.workspace}}/coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests_coverage
          path: ${{github.workspace}}/coverage

  e2e_client:
    name: End-to-end tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: e2e/go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up prebuilt werf test binary
        uses: ./.github/actions/set-up-prebuilt-trdl-test-binary
        with:
          coverage: "true"

      - name: Set up git config
        run: task ci:setup:git-config

      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg

      - name: Install 3p-git-signatures
        uses: task ci:install:3p-git-signatures

      - name: Install ginkgo
        working-directory: e2e
        run: task -p deps:install:ginkgo

      - name: Test
        run: task -p test:e2e
        env:
          GOCOVERDIR: ${{github.workspace}}/covdata

      - name: Upload coverage artifact
        uses: ./.github/actions/upload-coverage-artifact
        with:
          coverage: "true"

  notification:
    name: Notification
    if: always()
    needs:
      - tests
      - e2e_tests
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
