name: Broken links checker
on:
  push:
    branches: [main]
    paths:
      - docs
  schedule:
    - cron: "0 8 * * *"
  pull_request:
  repository_dispatch:
    types: [check-broken-links]
  workflow_dispatch:

jobs:
  check_links:
    name: Links checker
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        lang: [ru, en]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check ru broken links 
        if: matrix.lang == 'ru'
        run: task docs:check-broken-links

      - name: Check en broken links
        if: matrix.lang == 'en'
        run: task docs:check-broken-links language=en

  notification:
    name: Notification
    if: always()
    needs: check_links
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
