name: Review env Dismiss
on:
  pull_request:
    types: [closed, unlabeled]
  workflow_dispatch:

env:
  WERF_REPO: "ghcr.io/${{ github.repository_owner }}/trdl"

jobs:

  dismiss:
    name: Dismiss
    runs-on: ubuntu-latest-4-cores
    if: github.event.label.name == 'review docs' || contains( github.event.pull_request.labels.*.name, 'review docs' )
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dismiss
      uses: werf/actions/dismiss@v1.2
      continue-on-error: true
      with:
        env: review-${{ github.event.number }}
        kube-config-base64-data: ${{ secrets.KUBECONFIG_BASE64_DEV }}
      env:
        WERF_DIR: "docs"
        WERF_WITH_NAMESPACE: true
